Repository stackabletech/integration-test-commons, pull requests merged in 2021-08, with the labels that each got.

#15 Changed kube-rs to 0.58
  CHANGELOG.adoc
  Cargo.toml
Labels: type/dependencies

#17 Improve (hopefully) message while waiting for cluster to be ready
  src/operator/setup.rs
Labels: priority/low, type/enhancement

#19 Add checks for version and creation timestamps and improved logging
  CHANGELOG.adoc
  src/operator/setup.rs
Labels: priority/medium, type/enhancement

#20 Project updates
  .github/workflows/rust.yml
  Cargo.toml
  deny.toml
Labels: priority/low, type/enhancement

#21 Removed Conditions trait from cluster. Improved label selectors.
  CHANGELOG.adoc
  Cargo.toml
  src/operator/setup.rs
Labels: priority/medium, type/dependencies, type/enhancement
